services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 6472:5432

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6473:6379